import { readFileSync } from "node:fs";
import {
  loadBlokResponsibilityMetric,
  routingForDiscussionSlug,
} from "./blok-responsibility-metric";
import {
  addDiscussionCommentGraphql,
  addDiscussionLabelsByName,
} from "./github-discussion-graphql";
import { postTeamsDiscussionCreated } from "./teams-notify";

const api = process.env.GITHUB_API_URL || "https://api.github.com";
const token = process.env.GITHUB_TOKEN;
const repo = process.env.GITHUB_REPOSITORY;
const eventPath = process.env.GITHUB_EVENT_PATH;
if (!repo || !token || !eventPath) {
  console.error(
    "GITHUB_REPOSITORY, GITHUB_TOKEN, or GITHUB_EVENT_PATH missing",
  );
  process.exit(1);
}
const ghToken = token;
const event = JSON.parse(readFileSync(eventPath, "utf8")) as {
  discussion?: {
    number: number;
    node_id?: string;
    title: string;
    html_url: string;
    body?: string;
    category?: { slug?: string; name?: string };
    user?: { login?: string };
  };
};
const [owner, repoName] = repo.split("/");
const ownerEnc = encodeURIComponent(owner);
const repoEnc = encodeURIComponent(repoName);

async function gh(
  method: string,
  path: string,
  body: Record<string, unknown> | null,
): Promise<unknown> {
  const res = await fetch(`${api.replace(/\/+$/, "")}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${ghToken}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(body ? { "Content-Type": "application/json" } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`${method} ${path} → ${res.status}: ${text.slice(0, 800)}`);
  }
  return text ? (JSON.parse(text) as unknown) : {};
}

function sectionTitle(categorySlug: string, categoryName: string): string {
  const n = categoryName.trim();
  if (n) return n;
  return categorySlug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

function followUpLine(categorySlug: string): string {
  const bySlug: Record<string, string> = {
    "bug-reports":
      "Our team will review the bug as soon as possible and get back to you.",
    "feature-requests":
      "Our team will review your feature request as soon as possible and get back to you.",
    ideas:
      "Our team will review your idea as soon as possible and get back to you.",
    "general-q-a":
      "Our team will review your question as soon as possible and get back to you.",
    "design-feedback":
      "Our team will review your design feedback as soon as possible and get back to you.",
  };
  return (
    bySlug[categorySlug] ||
    "Our team will review this discussion as soon as possible and get back to you."
  );
}

function buildComment(
  categorySlug: string,
  categoryName: string,
  mentions: string,
): string {
  const section = sectionTitle(categorySlug, categoryName);
  const followUp = followUpLine(categorySlug);
  const cc = (mentions || "").trim();
  const ccBlock = cc ? `\n\nCC: ${cc}` : "";
  return `Thank you for opening this discussion in the ${section} section.

${followUp}${ccBlock}

This is an automated message generated by the community system.`;
}

async function main(): Promise<void> {
  const discussion = event.discussion;
  if (!discussion) {
    console.log("No discussion on event");
    process.exit(0);
  }

  const slug = discussion.category?.slug || "";
  const name = discussion.category?.name || slug;
  const metric = loadBlokResponsibilityMetric();
  const routing = routingForDiscussionSlug(slug, metric);
  const mentions = (routing.githubCc || "").trim();

  const commentBody = buildComment(slug, name, mentions);
  const number = discussion.number;
  const nodeId = discussion.node_id;

  if (nodeId) {
    await addDiscussionCommentGraphql({
      token: ghToken,
      discussionNodeId: nodeId,
      body: commentBody,
    });
    console.log("Posted welcome comment on discussion", number, "(GraphQL)");
  } else {
    await gh(
      "POST",
      `/repos/${ownerEnc}/${repoEnc}/discussions/${number}/comments`,
      {
        body: commentBody,
      },
    );
    console.log("Posted welcome comment on discussion", number, "(REST)");
  }

  try {
    if (nodeId) {
      await addDiscussionLabelsByName({
        token: ghToken,
        owner,
        repo: repoName,
        discussionNodeId: nodeId,
        labelNames: ["needs-triage"],
      });
      console.log("Applied label needs-triage (GraphQL)");
    } else {
      await gh(
        "PUT",
        `/repos/${ownerEnc}/${repoEnc}/discussions/${number}/labels`,
        {
          labels: ["needs-triage"],
        },
      );
      console.log("Applied label needs-triage (REST)");
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.warn(
      "Could not apply needs-triage label (create the label under Issues → Labels, or adjust token permissions):",
      msg,
    );
  }

  let discussionBody = (discussion.body || "").trim();
  if (!discussionBody && nodeId) {
    try {
      const full = (await gh(
        "GET",
        `/repos/${ownerEnc}/${repoEnc}/discussions/${number}`,
        null,
      )) as { body?: string };
      discussionBody = (full.body || "").trim();
    } catch {
      /* keep empty */
    }
  }

  const teamsUrl =
    process.env.TEAMS_COMMUNITY_WEBHOOK_URL || process.env.TEAMS_WEBHOOK_URL;
  if (teamsUrl) {
    await postTeamsDiscussionCreated({
      webhookUrl: teamsUrl,
      title: discussion.title,
      url: discussion.html_url,
      category: name,
      author: discussion.user?.login || "",
      repository: repo,
      discussionNumber: number,
      body: discussionBody,
      teamsMentions: routing.teamsMentions,
    });
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
