name: "Design Feedback"
description: Share feedback on UI components or design patterns in the Blok CN.
labels: ["design", "feedback"]
title: "[Design Feedback]: "
about: We appreciate your design insights! Help us improve the UI experience.
template: |
  ## Which component or pattern are you giving feedback on?
  _Example: Alert, Alert Dialog, Button, etc._

  ## What do you like about it?
  Share the strengths or positive aspects you’ve noticed.

  ## What could be improved?
  Suggest areas where this design/component could be better.

  ## Any references or examples?
  Provide links, screenshots, or design inspiration that could help us understand your feedback.
