name: "Feature Request"
description: Suggest a new feature or enhancement for the Sitecore Blok CN.
labels: ["enhancement", "feature request"]
title: "[Feature]: "
about: Thank you for suggesting a feature! Please fill out the details below.
template: |
  ## Is your feature request related to a problem?
  Describe the problem you're facing that this feature would solve.  
  _Example: "I'm always frustrated when..."_

  ## Describe the solution you'd like
  What would you like to see implemented?

  ## Describe alternatives you've considered
  Have you thought of other ways to solve this problem?

  ## Additional context
  Add any other context or screenshots about the feature request here.
