name: "General Q&A"
description: Ask questions or start a general discussion about the Sitecore Blok CN UI library.
labels: ["question", "discussion"]
title: "[Q&A]: "
about: Welcome! Feel free to ask questions or start a conversation.
template: |
  ## What's your question or topic?
  Describe what you'd like to discuss.

  ## Additional details
  Provide any background or context.
