name: "Help"
description: Request help or support for using the Sitecore Blok CN UI library.
labels: [help wanted, support]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Fill out the form below and we'll do our best to assist you.
  - type: textarea
    id: issue
    attributes:
      label: What do you need help with?
      description: Describe the issue or question you have.
    validations:
      required: true
  - type: textarea
    id: attempts
    attributes:
      label: What have you tried so far?
      description: Let us know what you've already attempted.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant information or screenshots.
    validations:
      required: false
