name: "Help"
description: Request help or support for using the Sitecore Blok CN UI library.
labels: ["help wanted", "support"]
title: "[Help]: "
about: Need help? Fill out the form below and we'll do our best to assist you.
template: |
  ## What do you need help with?
  Describe the issue or question you have.

  ## What have you tried so far?
  Let us know what you've already attempted.

  ## Additional context
  Any other relevant information or screenshots.
