name: "Ideas"
description: Share creative ideas or improvements for Sitecore Blok CN the UI library.
labels: ["idea", "brainstorming"]
title: "[Idea]: "
about: Got a cool idea? We'd love to hear it!
template: |
  ## Describe your idea
  What is your idea and how could it improve the project?

  ## What are the benefits?
  How would this idea help users or developers?

  ## Additional context
  Any other relevant information or examples.
