name: 'Setup and Build Application'
description: 'Setup Node.js, install dependencies, and build the Next.js application'

inputs:
  app-path:
    description: 'Path to the application directory'
    required: true
    default: 'app'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: 'lts/*'

outputs:
  build-status:
    description: 'Build status (success or failed)'
    value: ${{ steps.build.outputs.build-status }}
  build-exit-code:
    description: 'Build exit code'
    value: ${{ steps.build.outputs.build-exit-code }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.app-path }}/package-lock.json
    
    - name: Install app dependencies
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: npm ci
    
    - name: Clean up extra lockfiles
      shell: bash
      run: |
        # Remove any package-lock.json in nested app/ subdirectory that might confuse Next.js
        # Next.js detects multiple lockfiles and treats them as separate workspaces
        # This causes path resolution issues with Turbopack
        if [ -f "${{ inputs.app-path }}/app/package-lock.json" ]; then
          echo "⚠️ Found nested app/package-lock.json - removing to prevent Next.js workspace confusion"
          rm -f "${{ inputs.app-path }}/app/package-lock.json"
          echo "✅ Removed nested lockfile"
        else
          echo "✅ No nested lockfiles found"
        fi
    
    - name: Build Next.js application
      id: build
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      continue-on-error: true
      run: |
        set +e
        npm run build
        BUILD_EXIT_CODE=$?
        echo "build-exit-code=${BUILD_EXIT_CODE}" >> $GITHUB_OUTPUT
        if [ $BUILD_EXIT_CODE -eq 0 ]; then
          echo "build-status=success" >> $GITHUB_OUTPUT
          echo "Build completed successfully"
        else
          echo "build-status=failed" >> $GITHUB_OUTPUT
          echo "Build failed with exit code: $BUILD_EXIT_CODE"
          echo "=== Build Error Output ==="
          npm run build 2>&1 | tail -50 || true
        fi
        exit $BUILD_EXIT_CODE
      env:
        NODE_ENV: production

