name: 'Setup and Build Application'
description: 'Setup Node.js, install dependencies, install components, and build the Next.js application'

inputs:
  app-path:
    description: 'Path to the application directory'
    required: true
    default: 'app'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: 'lts/*'

outputs:
  build-status:
    description: 'Build status (success or failed)'
    value: ${{ steps.build.outputs.build-status }}
  build-exit-code:
    description: 'Build exit code'
    value: ${{ steps.build.outputs.build-exit-code }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.app-path }}/package-lock.json
    
    - name: Install app dependencies
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: npm ci
    
    - name: Clean up extra lockfiles
      shell: bash
      run: |
        # Remove any package-lock.json in nested app/ subdirectory that might confuse Next.js
        # Next.js detects multiple lockfiles and treats them as separate workspaces
        # This causes path resolution issues with Turbopack
        if [ -f "${{ inputs.app-path }}/app/package-lock.json" ]; then
          echo "⚠️ Found nested app/package-lock.json - removing to prevent Next.js workspace confusion"
          rm -f "${{ inputs.app-path }}/app/package-lock.json"
          echo "✅ Removed nested lockfile"
        else
          echo "✅ No nested lockfiles found"
        fi
    
    - name: Verify components.json location
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: |
        echo "=== Verifying Installation Path ==="
        echo "Current working directory: $(pwd)"
        echo ""
        echo "Checking for components.json:"
        if [ -f "components.json" ]; then
          echo "✅ components.json found at: $(pwd)/components.json"
          echo ""
          echo "Components will be installed to:"
          COMPONENTS_PATH=$(node -p "require('./components.json').aliases?.components || '@/components'")
          echo "  Path from components.json: $COMPONENTS_PATH"
          echo "  Resolved path: components/ui/ (relative to current directory)"
        else
          echo "❌ components.json NOT FOUND in $(pwd)"
          echo "Looking for components.json in parent directories..."
          find .. -name "components.json" -type f 2>/dev/null | head -3 || echo "  Not found"
          exit 1
        fi
    
    - name: Install Blok components
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: |
        echo "=== Installing components from configuration ==="
        echo "Working directory: $(pwd)"
        echo ""
        
        # Check if components-config.json exists
        if [ ! -f "components-config.json" ]; then
          echo "❌ components-config.json not found"
          exit 1
        fi
        
        echo "Found components-config.json, reading configuration..."
        
        # Step 1: Install bulk components if enabled (with --overwrite --yes)
        BULK_ENABLED=$(node -p "require('./components-config.json').bulkInstall?.enabled !== false")
        if [ "$BULK_ENABLED" = "true" ]; then
          BULK_URL=$(node -p "require('./components-config.json').bulkInstall?.url || ''")
          if [ -n "$BULK_URL" ] && [ "$BULK_URL" != "undefined" ]; then
            echo ""
            echo "Step 1: Installing bulk components from: $BULK_URL"
            echo "Using --overwrite --yes flags..."
            npx shadcn@latest add "$BULK_URL" --yes --overwrite || true
            echo "✅ Bulk component installation completed"
          fi
        else
          echo "Bulk installation is disabled, skipping..."
        fi
        
        # Step 2: Install all additional components (with --overwrite --yes)
        echo ""
        echo "Step 2: Installing all additional components from components-config.json..."
        echo "Using --overwrite --yes flags for all components..."
        node -e "
          const config = require('./components-config.json');
          if (config.additionalComponents && Array.isArray(config.additionalComponents)) {
            config.additionalComponents.forEach(url => {
              if (typeof url === 'string' && url.trim()) {
                console.log(url);
              }
            });
          }
        " | while IFS= read -r componentUrl; do
          if [ -n "$componentUrl" ]; then
            echo "  Installing: $componentUrl"
            npx shadcn@latest add "$componentUrl" --yes --overwrite 2>&1 || echo "    ⚠️ Failed to install (may not exist)"
            sleep 1
          fi
        done
        echo "✅ Additional component installation completed"
        
        # Step 3: Wait for installation to complete and ensure files are written
        echo ""
        echo "Step 3: Waiting for installation to complete and ensuring files are written..."
        sleep 15
        
        # Force filesystem sync to ensure all files are written to disk
        sync 2>/dev/null || true
        echo "  Filesystem synced"
        
        # Verify files are actually on disk
        if [ -d "components/ui" ]; then
          FILE_COUNT=$(find components/ui -name "*.tsx" -type f 2>/dev/null | wc -l)
          echo "  Component files on disk: $FILE_COUNT"
          
          # Try to read a few files to ensure they're accessible
          READABLE=0
          find components/ui -name "*.tsx" -type f 2>/dev/null | head -5 | while read file; do
            if [ -r "$file" ] && [ -s "$file" ]; then
              READABLE=$((READABLE + 1))
            fi
          done
          echo "  Verified $READABLE component files are readable"
        fi
        
        # CRITICAL: Verify globals.css was updated by shadcn CLI
        echo ""
        echo "Step 3.5: Verifying globals.css was updated by shadcn CLI..."
        if [ -f "app/globals.css" ]; then
          CSS_SIZE=$(wc -l < app/globals.css)
          echo "  globals.css size: $CSS_SIZE lines"
          
          # Check for key CSS variables that shadcn adds
          if grep -q ":root" app/globals.css && grep -q "--background\|--foreground" app/globals.css; then
            echo "  ✅ CSS variables found (shadcn updated the file)"
          else
            echo "  ⚠️ CSS variables not found - shadcn may not have updated globals.css properly"
          fi
          
          # Check for @layer base (critical for component styles)
          if grep -q "@layer base" app/globals.css; then
            echo "  ✅ @layer base found"
          else
            echo "  ⚠️ @layer base not found - this is required for component styles!"
          fi
          
          # Check for Tailwind import
          if grep -q "@import.*tailwindcss\|@tailwind" app/globals.css; then
            echo "  ✅ Tailwind import found"
          else
            echo "  ❌ Tailwind import missing - this will break styles!"
          fi
          
          # Touch the file to ensure build sees it as modified
          touch app/globals.css
          echo "  ✅ Touched globals.css to ensure build picks up changes"
        else
          echo "  ❌ globals.css not found!"
          exit 1
        fi
        
        sleep 2
        echo "✅ Wait completed - files should be ready"
        
        # Step 4: Verify and list all installed components
        echo ""
        echo "Step 4: Verifying installed components..."
        if [ -d "components/ui" ]; then
          COMPONENT_COUNT=$(find components/ui -name "*.tsx" 2>/dev/null | wc -l)
          echo "✅ Components installed to: $(pwd)/components/ui"
          echo ""
          echo "Total components installed: $COMPONENT_COUNT"
          echo ""
          echo "List of all installed components:"
          find components/ui -name "*.tsx" | sed 's|components/ui/||' | sed 's|\.tsx||' | sort
        else
          echo "❌ Components directory not found at: $(pwd)/components/ui"
          exit 1
        fi
    
    - name: Install dependencies after component installation
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: |
        echo "Installing dependencies that may have been added by component installation..."
        npm install
        echo "Dependencies installation completed"
    
    - name: Ensure globals.css is properly configured after component installation
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: |
        echo "=== Ensuring globals.css is properly configured ==="
        echo ""
        
        if [ ! -f "app/globals.css" ]; then
          echo "❌ globals.css not found!"
          exit 1
        fi
        
        # Check if @layer base exists (required for component styles)
        if ! grep -q "@layer base" app/globals.css; then
          echo "⚠️ @layer base not found in globals.css - adding it..."
          echo "" >> app/globals.css
          echo "@layer base {" >> app/globals.css
          echo "  * {" >> app/globals.css
          echo "    @apply border-border outline-ring/50;" >> app/globals.css
          echo "  }" >> app/globals.css
          echo "  body {" >> app/globals.css
          echo "    @apply bg-background text-foreground;" >> app/globals.css
          echo "  }" >> app/globals.css
          echo "}" >> app/globals.css
          echo "✅ Added @layer base to globals.css"
        else
          echo "✅ @layer base already exists in globals.css"
        fi
        
        # Verify Tailwind import exists
        if ! grep -q "@import.*tailwindcss\|@tailwind" app/globals.css; then
          echo "⚠️ Tailwind import not found - this is critical!"
          echo "Current first few lines of globals.css:"
          head -5 app/globals.css
          exit 1
        else
          echo "✅ Tailwind import found in globals.css"
        fi
        
        # Verify CSS variables are present (needed for components)
        if ! grep -q "--background\|--foreground" app/globals.css; then
          echo "⚠️ CSS variables not found - components may not style correctly"
        else
          echo "✅ CSS variables found in globals.css"
        fi
        
        echo ""
        echo "=== CSS Configuration Complete ==="
    
    - name: Verify component styles and CSS
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: |
        echo "=== Verifying CSS and Component Setup ==="
        echo ""
        echo "Checking globals.css exists:"
        if [ -f "app/globals.css" ]; then
          echo "✅ globals.css found"
          CSS_SIZE=$(wc -l < app/globals.css)
          echo "  CSS file size: $CSS_SIZE lines"
        else
          echo "❌ globals.css not found!"
          exit 1
        fi
        echo ""
        echo "Checking for Tailwind imports in globals.css:"
        if grep -q "@import.*tailwind" app/globals.css || grep -q "@tailwind" app/globals.css; then
          echo "✅ Tailwind imports found in globals.css"
        else
          echo "⚠️ Tailwind imports not found - this might cause styling issues"
        fi
        echo ""
        echo "Verifying components have proper imports:"
        SAMPLE_COMPONENT=$(find components/ui -name "*.tsx" | head -1)
        if [ -n "$SAMPLE_COMPONENT" ]; then
          echo "Checking sample component: $SAMPLE_COMPONENT"
          if grep -q "cn\|className" "$SAMPLE_COMPONENT" 2>/dev/null; then
            echo "✅ Component uses className/cn utility"
          fi
        fi
    
    - name: Clear Next.js cache and ensure fresh build
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: |
        echo "Clearing Next.js cache to ensure fresh build with components..."
        rm -rf .next
        rm -rf node_modules/.cache
        rm -rf .turbo
        echo "✅ Cache cleared"
        
        # Verify components are present before build
        echo ""
        echo "Verifying components are installed before build..."
        if [ -d "components/ui" ]; then
          COMPONENT_COUNT=$(find components/ui -name "*.tsx" 2>/dev/null | wc -l)
          echo "  Components ready: $COMPONENT_COUNT"
          
          # Check a sample component to ensure it has Tailwind classes
          SAMPLE=$(find components/ui -name "*.tsx" | head -1)
          if [ -n "$SAMPLE" ]; then
            if grep -q "className\|cn(" "$SAMPLE" 2>/dev/null; then
              echo "  ✅ Sample component uses Tailwind classes"
              echo ""
              echo "  Sample component classes found:"
              grep -o "className=\"[^\"]*\"" "$SAMPLE" 2>/dev/null | head -3 | sed 's/^/    /' || true
            else
              echo "  ⚠️ Sample component may not use Tailwind classes"
            fi
          fi
          
          # Ensure all component files are fully written (flush filesystem)
          echo ""
          echo "Ensuring all component files are fully written..."
          sync 2>/dev/null || true
          sleep 2
          echo "  ✅ File system synced"
        else
          echo "  ❌ Components directory not found!"
          exit 1
        fi
        
        # Verify globals.css is accessible and has correct imports
        echo ""
        echo "Final check of globals.css before build..."
        if [ -f "app/globals.css" ]; then
          if grep -q "@import.*tailwindcss\|@tailwind" app/globals.css; then
            echo "  ✅ globals.css has Tailwind import"
          else
            echo "  ❌ globals.css missing Tailwind import!"
            exit 1
          fi
        fi
    
    - name: Force Tailwind to rescan component files
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      run: |
        echo "=== Forcing Tailwind to recognize new component files ==="
        echo ""
        
        # Touch globals.css to ensure it's seen as modified (forces CSS regeneration)
        if [ -f "app/globals.css" ]; then
          touch app/globals.css
          echo "✅ Touched globals.css to trigger CSS regeneration"
        fi
        
        # Ensure component files are readable and have correct permissions
        if [ -d "components/ui" ]; then
          echo "Verifying component file accessibility..."
          find components/ui -name "*.tsx" -type f | head -5 | while read file; do
            if [ -r "$file" ]; then
              echo "  ✅ $file is readable"
            else
              echo "  ❌ $file is not readable!"
              chmod 644 "$file" 2>/dev/null || true
            fi
          done
        fi
        
        # List component files to ensure they exist (helps with debugging)
        echo ""
        echo "Component files that will be included in build:"
        find components/ui -name "*.tsx" 2>/dev/null | wc -l | xargs echo "  Total:"
        echo ""
        echo "✅ Ready for build"
    
    - name: Build Next.js application
      id: build
      shell: bash
      working-directory: ./${{ inputs.app-path }}
      continue-on-error: true
      run: |
        set +e
        echo "Building Next.js application with components..."
        echo "This build will include all installed components and their styles..."
        npm run build
        BUILD_EXIT_CODE=$?
        echo "build-exit-code=${BUILD_EXIT_CODE}" >> $GITHUB_OUTPUT
        if [ $BUILD_EXIT_CODE -eq 0 ]; then
          echo "build-status=success" >> $GITHUB_OUTPUT
          echo "Build completed successfully"
          
          # Verify build output includes CSS
          echo ""
          echo "=== Verifying Build Output ==="
          if [ -d ".next" ]; then
            echo "✅ .next directory created"
            
            # Check for CSS files in build output
            CSS_FILES=$(find .next -name "*.css" 2>/dev/null | wc -l)
            echo "  CSS files in build: $CSS_FILES"
            
            if [ $CSS_FILES -gt 0 ]; then
              echo "  ✅ CSS files found in build output"
              # Check if CSS contains component-related classes
              SAMPLE_CSS=$(find .next -name "*.css" -type f 2>/dev/null | head -1)
              if [ -n "$SAMPLE_CSS" ] && [ -f "$SAMPLE_CSS" ]; then
                CSS_SIZE=$(wc -c < "$SAMPLE_CSS" 2>/dev/null || echo "0")
                echo "  Sample CSS file size: $CSS_SIZE bytes"
                
                # Check for component-related CSS classes/variables
                if grep -q "bg-background\|text-foreground\|border-border" "$SAMPLE_CSS" 2>/dev/null; then
                  echo "  ✅ CSS contains component styles (background, foreground, border)"
                else
                  echo "  ⚠️ CSS may not contain component styles"
                fi
              fi
            else
              echo "  ⚠️ No CSS files found in build output - this is a problem!"
            fi
            
            # Check for component files
            if [ -d "components/ui" ]; then
              COMPONENT_COUNT=$(find components/ui -name "*.tsx" 2>/dev/null | wc -l)
              echo "  Components available: $COMPONENT_COUNT"
            fi
            
            # Verify static assets
            if [ -d ".next/static" ]; then
              echo "✅ Static assets directory exists"
            fi
            
            # CRITICAL: Verify globals.css is still correct after build
            echo ""
            echo "Verifying globals.css after build..."
            if [ -f "app/globals.css" ]; then
              if grep -q "@import.*tailwindcss\|@tailwind" app/globals.css; then
                echo "  ✅ globals.css still has Tailwind import"
              else
                echo "  ❌ globals.css missing Tailwind import after build!"
              fi
            fi
          else
            echo "⚠️ .next directory not found after build"
          fi
        else
          echo "build-status=failed" >> $GITHUB_OUTPUT
          echo "Build failed with exit code: $BUILD_EXIT_CODE"
          echo "=== Build Error Output ==="
          npm run build 2>&1 | tail -50 || true
        fi
        exit $BUILD_EXIT_CODE
      env:
        NODE_ENV: production

