import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import "./globals.css"
import TopBar from "@/components/layout/topbar"
import { SidebarProvider } from "@/registry/new-york/ui/sidebar"
import { Toaster } from "@/registry/new-york/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider className="w-full h-screen flex flex-col overflow-y-hidden">
          <header className="bg-background sticky inset-x-0 top-0 isolate z-10 flex shrink-0 items-center gap-2 border-b">
            <div className="flex h-14 w-full items-center gap-2 px-4">
              <TopBar />
            </div>
          </header>
          <main className="flex-1 overflow-y-auto">
            {children}
          </main>
          <Toaster />
        </SidebarProvider>
      </body>
    </html>
  )
}
