name: 'Upload Test Artifacts'
description: 'Upload Playwright test reports and server logs'

inputs:
  tests-path:
    description: 'Path to the tests directory'
    required: true
    default: 'tests'
  app-path:
    description: 'Path to the application directory'
    required: true
    default: 'app'
  report-retention-days:
    description: 'Number of days to retain test reports'
    required: false
    default: '30'
  logs-retention-days:
    description: 'Number of days to retain server logs'
    required: false
    default: '7'

runs:
  using: 'composite'
  steps:
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ${{ inputs.tests-path }}/playwright-report/
        retention-days: ${{ inputs.report-retention-days }}
      continue-on-error: true
    
    - name: Upload server logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: server-logs
        path: ${{ inputs.app-path }}/server.log
        retention-days: ${{ inputs.logs-retention-days }}
      continue-on-error: true

