export interface SitePermissions {
  canAdmin: boolean;
  canCreate: boolean;
  canRead: boolean;
  canDelete: boolean;
  canWrite: boolean;
  canRename: boolean;
}

export interface SiteHost {
  id: string;
  name: string;
  hostnames: string[];
  targetHostname: string;
}

export interface SiteThumbnail {
  url: string;
  rootPath: string;
  autogenerated: boolean;
}

export interface SiteFavoritesResponse {
  id: string;
  name: string;
  description: string;
  displayName: string;
  thumbnailUrl: string;
  collectionId: string;
  collectionName?: string;
  thumbnail: SiteThumbnail;
  permissions: SitePermissions;
  hosts: SiteHost[];
  portfolioAccess?: SitePermissions;
}

/** Mock data for pinned sites (from API). */
export const mockPinnedSites: SiteFavoritesResponse[] = [
  {
    id: "site-abc-123",
    name: "my-ecommerce-site",
    displayName: "My Ecommerce Site",
    description: "Our main ecommerce website",
    collectionId: "portfolio-456",
    thumbnailUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23fb923c'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3EMarketing%3C/text%3E%3C/svg%3E",
    thumbnail: {
      url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23fb923c'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3EMarketing%3C/text%3E%3C/svg%3E",
      rootPath: "/thumbnails/",
      autogenerated: true,
    },
    permissions: {
      canAdmin: true,
      canWrite: true,
      canCreate: true,
      canDelete: true,
      canRename: true,
      canRead: true,
    },
    hosts: [
      {
        id: "host-001",
        name: "Production Host",
        hostnames: ["www.mysite.com", "mysite.com"],
        targetHostname: "prod.mysite.com",
      },
    ],
  },
  {
    id: "site-xyz-456",
    name: "corporate-blog",
    displayName: "Corporate Blog",
    description: "Company blog and news",
    collectionId: "portfolio-789",
    thumbnailUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23a78bfa'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3ECorporate Blog%3C/text%3E%3C/svg%3E",
    thumbnail: {
      url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23a78bfa'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3ECorporate Blog%3C/text%3E%3C/svg%3E",
      rootPath: "/thumbnails/",
      autogenerated: false,
    },
    permissions: {
      canAdmin: true,
      canWrite: true,
      canCreate: true,
      canDelete: false,
      canRename: true,
      canRead: true,
    },
    hosts: [
      {
        id: "host-002",
        name: "Production Host",
        hostnames: ["blog.company.com", "www.blog.company.com"],
        targetHostname: "blog.company.com",
      },
    ],
  },
];

/** Mock data for all available sites (from API). */
export const mockAllSites: SiteFavoritesResponse[] = [
  {
    id: "site-def-789",
    name: "marketing-site",
    displayName: "Marketing Site",
    description: "Landing pages for campaigns",
    collectionId: "portfolio-123",
    thumbnailUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23fb923c'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3EMarketing%3C/text%3E%3C/svg%3E",
    thumbnail: {
      url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23fb923c'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3EMarketing%3C/text%3E%3C/svg%3E",
      rootPath: "/thumbnails/",
      autogenerated: true,
    },
    permissions: {
      canAdmin: false,
      canWrite: true,
      canCreate: true,
      canDelete: false,
      canRename: true,
      canRead: true,
    },
    hosts: [
      {
        id: "host-003",
        name: "Campaign Host",
        hostnames: ["marketing.example.com"],
        targetHostname: "marketing.example.com",
      },
    ],
  },
  {
    id: "site-ghi-101",
    name: "partner-portal",
    displayName: "Partner Portal",
    description: "Portal for business partners",
    collectionId: "portfolio-456",
    thumbnailUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%2334d399'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3EPartner Portal%3C/text%3E%3C/svg%3E",
    thumbnail: {
      url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%2334d399'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3EPartner Portal%3C/text%3E%3C/svg%3E",
      rootPath: "/thumbnails/",
      autogenerated: false,
    },
    permissions: {
      canAdmin: false,
      canWrite: true,
      canCreate: false,
      canDelete: false,
      canRename: false,
      canRead: true,
    },
    hosts: [
      {
        id: "host-004",
        name: "Portal Host",
        hostnames: ["partners.example.com"],
        targetHostname: "partners.example.com",
      },
    ],
  },
  {
    id: "site-jkl-202",
    name: "customer-support",
    displayName: "Customer Support",
    description: "Help center and support documentation",
    collectionId: "portfolio-789",
    thumbnailUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23f472b6'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3ESupport%3C/text%3E%3C/svg%3E",
    thumbnail: {
      url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23f472b6'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3ESupport%3C/text%3E%3C/svg%3E",
      rootPath: "/thumbnails/",
      autogenerated: true,
    },
    permissions: {
      canAdmin: false,
      canWrite: true,
      canCreate: true,
      canDelete: false,
      canRename: true,
      canRead: true,
    },
    hosts: [
      {
        id: "host-005",
        name: "Support Host",
        hostnames: ["support.example.com", "help.example.com"],
        targetHostname: "support.example.com",
      },
    ],
  },
  {
    id: "site-mno-303",
    name: "documentation",
    displayName: "Documentation",
    description: "Technical documentation and API references",
    collectionId: "portfolio-123",
    thumbnailUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%2364748b'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3EDocs%3C/text%3E%3C/svg%3E",
    thumbnail: {
      url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%2364748b'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3EDocs%3C/text%3E%3C/svg%3E",
      rootPath: "/thumbnails/",
      autogenerated: false,
    },
    permissions: {
      canAdmin: false,
      canWrite: true,
      canCreate: true,
      canDelete: false,
      canRename: true,
      canRead: true,
    },
    hosts: [
      {
        id: "host-006",
        name: "Docs Host",
        hostnames: ["docs.example.com", "api.example.com"],
        targetHostname: "docs.example.com",
      },
    ],
  },
  ...mockPinnedSites,
];

export const initialPinnedSiteIds = mockPinnedSites.map((site) => site.id);
