export interface SitePermissions {
    canAdmin: boolean;
    canCreate: boolean;
    canRead: boolean;
    canDelete: boolean;
    canWrite: boolean;
    canRename: boolean;
  }
  
  export interface SiteHost {
    id: string;
    name: string;
    hostnames: string[];
    targetHostname: string;
  }
  
  export interface SiteThumbnail {
    url: string;
    rootPath: string;
    autogenerated: boolean;
  }
  
  export interface SiteCardMockSite {
    id: string;
    name: string;
    description: string;
    displayName: string;
    thumbnailUrl: string;
    collectionId: string;
    collectionName?: string;
    thumbnail: SiteThumbnail;
    permissions: SitePermissions;
    hosts: SiteHost[];
  }
  
  export const mockSite: SiteCardMockSite = {
    id: "site-demo-001",
    name: "demo-site",
    displayName: "Demo Site",
    description: "A demo site for testing",
    collectionId: "collection-001",
    collectionName: "Demo Collection",
    thumbnailUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23a78bfa'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3ECorporate Blog%3C/text%3E%3C/svg%3E",
    thumbnail: {
      url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='225'%3E%3Crect width='400' height='225' fill='%23a78bfa'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='white' font-family='sans-serif' font-size='24'%3ECorporate Blog%3C/text%3E%3C/svg%3E",
      rootPath: "/thumbnails/",
      autogenerated: false,
    },
    permissions: {
      canAdmin: true,
      canCreate: true,
      canRead: true,
      canDelete: true,
      canWrite: true,
      canRename: true,
    },
    hosts: [
      {
        id: "host-001",
        name: "Main Host",
        hostnames: ["demo.example.com"],
        targetHostname: "demo.example.com",
      },
    ],
  };
  